# -*- coding: utf-8 -*-
"""Approximating the derivative

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sDzsDhDpwU7ypyn2sx2IJ3RJlw-RSief
"""

!pip install gitpython

def D2(f, x, h=1E-6):
  return (f(x-h) - 2*f(x) + f(x+h)) / (h*h)

from math import sin
D2(sin, 0.2)

-sin(0.2)

def g(x):
  return sin(2*x)
D2(g, 0.2)

D2(lambda x: sin(2*x), 0.2) # central diff approximation

-4*sin(2* 0.2) # actual 2nd derivative value

print(' h D2 Result Error')
for k in range(4,8):
  h = 2**(-k)
  d2g = D2(lambda x: x**-6, 1, h=h)
  e = d2g - 42
  print('%.0e %.5f %7.6f' %(h, d2g, e))

for k in range(1,14):
  h = 10**(-k)
  d2g = D2(lambda x: x**-6,1, h)
  print('%.0e %18.5f' %(h, d2g))

