# -*- coding: utf-8 -*-
"""Genome of SARS-CoV-2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PLSAYSNU70h7pIfAsAcODplAyUavyKDQ
"""

!pip install gitpython

# NCBI url:
url = 'https://www.ncbi.nlm.nih.gov/sviewer/viewer.cgi?tool=portal&' + \
'save=file&log$=seqview&db=nuccore&report=fasta&id=1798174254&' + \
'extrafeat=null&conwithfeat=on&hide-cdd=on'
# your local downloaded file:
f = '../../data_external/SARS-CoV-2-Wuhan-NC_045512.2.fasta'

import os
import urllib
import shutil
if not os.path.isdir('../../data_external/'):
  os.mkdir('../../data_external/')
r = urllib.request.urlopen(url)
fo = open(f, 'wb')
shutil.copyfileobj(r, fo)
fo.close()

lines = open(f, 'r').readlines()

lines[0:5]

lines[1].strip()

rna = ''.join([line.strip() for line in lines[1:]])

rna[:1000]

rna[-1000:]

len(rna)

orf7a = ('augaaaauuauucuuuucuuggcacugauaacacucgcuacuugugagcuuuaucacuaccaag'
        'aguguguuagagguacaacaguacuuuuaaaagaaccuugcucuucuggaacauacgagggcaa'
        'uucaccauuucauccucuagcugauaacaaauuugcacugacuugcuuuagcacucaauuugcu'
        'uuugcuuguccugacggcguaaaacacgucuaucaguuacgugccagaucaguuucaccuaaac'
        'uguucaucagacaagaggaaguucaagaacuuuacucuccaauuuuucuuauuguugcggcaau'
        'aguguuuauaacacuuugcuucacacucaaaagaaagacagaaugauugaacuuucauuaauug'
        'acuucuauuugugcuuuuuagccuuucugcuauuccuuguuuuaauuaugcuuauuaucuuuug'
        'guucucacuugaacugcaagaucauaaugaaacuugucacgccuaaacgaac')

s=orf7a.replace('u', 'T').replace('a', 'A').replace('g', 'G').replace('c','C')
s

s in rna

rna.find(s)

rna[27393:]

freq = {b: rna.count(b)/len(rna) for b in 'ATGC'}

freq

url2 = 'https://www.ncbi.nlm.nih.gov/sviewer/viewer.cgi?' + \
'tool=portal&save=file&log$=seqview&db=nuccore&report=fasta&' + \
'id=1828694245&extrafeat=null&conwithfeat=on&hide-cdd=on'
f2 = '../../data_external/SARS-CoV-2-Washington_MT293201.1.fasta'

r2 = urllib.request.urlopen(url2)
fo2 = open(f2, 'wb')
shutil.copyfileobj(r2, fo2)

lines = open(f2, 'r').readlines()
rna2 = ''.join([line.strip() for line in lines[1:]])

set(rna2)

len(rna2), len(rna)

rna2[:30], rna2[-30:]

rna[:30], rna[-30:]

freq2 = {b: rna2.count(b)/len(rna2) for b in 'ATGC'}

freq2

freq

s in rna2

rna2.find(s)

