# -*- coding: utf-8 -*-
"""Google’s toy graph

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TRRcy20A2SxlfT9PK9gox1zFydCeYuwB
"""

import os
import urllib.request
import shutil
import numpy as np

# The URL for the Google Web Graph data
url = "https://snap.stanford.edu/data/web-Google.txt.gz"

# The file path to save the downloaded data
data_file = 'web-Google.txt.gz'

# Download and copy the data file
if not os.path.exists(data_file):
    with urllib.request.urlopen(url) as response, open(data_file, 'wb') as out_file:
        shutil.copyfileobj(response, out_file)

# After downloading the file, you can use the code provided in my previous response to process the data and compute PageRank.

