# -*- coding: utf-8 -*-
"""Growth of COVID- 19  cases in the west coast

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qyA0rJHO58Yw3ky2dccgF-0V4M4fXnYb
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install gitpython  #install gitpython to access git repository data and to get covid data

import pandas as pd #Imports the Pandas library for data manipulation.
import os #Imports the os module for interacting with the operating system.
from git.repo import Repo #Imports the Repo class from the git.repo module
import matplotlib.pyplot as plt #Imports the Matplotlib library for creating plots
import geopandas as gpd # Imports the GeoPandas library for working with geospatial data.
import urllib # imports the urllib module for working with URLs.
import shutil #  Imports the shutil module for file operations.
# %matplotlib inline

# your local folder into which you want to download the covid data
covidfolder = '../../data_external/covid19'

if os.path.isdir(covidfolder): # if repo exists, pull newest data
    repo = Repo(covidfolder)
    repo.remotes.origin.pull()
else: # otherwise, clone from remote
    repo = Repo.clone_from('https://github.com/CSSEGISandData/COVID-19.git',covidfolder)

# Combines the covidfolder path with the relative path to the CSV file
#containing confirmed COVID-19 cases in the United States.
datadir = os.path.join(covidfolder, 'csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv')

covid_data = pd.read_csv(datadir) # Reads the CSV file into a Pandas DataFrame called covid_data.

# Filter the data for Oregon, Washington, and California
oregon_data = covid_data[covid_data['Province_State'] == 'Oregon']
washington_data = covid_data[covid_data['Province_State'] == 'Washington']
california_data = covid_data[covid_data['Province_State'] == 'California']

# Extract the date columns and cases for each state
oregon_cases = oregon_data.iloc[:, 11:]
washington_cases = washington_data.iloc[:, 11:]
california_cases = california_data.iloc[:, 11:]
# oregon_cases, washington_cases, and california_cases are created
#by selecting the columns containing the COVID-19 cases data for each state.

# Convert the date columns to datetime objects
dates = pd.to_datetime(oregon_cases.columns)

# Plot the time series of confirmed cases for each state
plt.figure(figsize=(12, 6))
plt.plot(dates, oregon_cases.iloc[0], label='Oregon')
plt.plot(dates, washington_cases.iloc[0], label='Washington')
plt.plot(dates, california_cases.iloc[0], label='California')

plt.title('COVID-19 Confirmed Cases Time Series (Oregon, Washington, California)')
plt.xlabel('Date')
plt.ylabel('Confirmed Cases')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)

plt.show()