# -*- coding: utf-8 -*-
"""Interacting with Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vLrL0Yisrb8SN0hV84r6KjC5SLH0ZIG2
"""

!pip install gitpython

from math import cos, sqrt, pi
cos(pi*sqrt(pi))**7

# %load ../pyfiles/myfirstpy.py
from math import cos, sqrt, pi
print('Hello, I can compute! ')
x = 3
y = cos(pi*sqrt(pi)*x)**7
print('Starting from x =', x, 'we have computed y=', y)

