# -*- coding: utf-8 -*-
"""pairwise diiference

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12vwzuqyTO-n9_vHAAuZvQ_Wpk9aygCV4
"""

!pip install gitpython

import numpy as np

# Generate a random 1D numpy array with 5 elements
x = np.random.rand(5)

# Create a 2D numpy array D where Dij = xi - xj in one line of code
# Use NumPy broadcasting to calculate the pairwise differences
D = x[:, np.newaxis] - x

# Print the original array x and the resulting 2D array D
print("Original 1D array x:")
print(x)
print("\n2D array D with pairwise differences (Dij = xi - xj):")
print(D)