# -*- coding: utf-8 -*-
"""Piecewise functions

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k2E_ieuMddxikdD9n_zT_Bt5HfuWQXoz
"""

import numpy as np
import matplotlib.pyplot as plt

# Step 1: Create an array of 1000001 uniformly spaced points in the interval [-5, 5]
x = np.linspace(-5, 5, 1000001)

# Step 2: Compute the function values based on the piecewise definition
# Use np.where to efficiently compute values based on conditions:
# - For x < 0, calculate x * sin(x^2)
# - For x >= 0, calculate cos(x)
y = np.where(x < 0, x * np.sin(x**2), np.cos(x))

# Step 3: Plot the function
plt.figure(figsize=(10, 6))  # Create a figure with a specified size
plt.plot(x, y, label='f(x)')  # Plot x against y with a label for the legend
plt.xlabel('x')  # Label the x-axis
plt.ylabel('f(x)')  # Label the y-axis
plt.title('Piecewise Function: x*sin(x^2) if x < 0, cos(x) if x >= 0')  # Set the plot title
plt.grid(True)  # Add a grid to the plot
plt.legend()  # Display the legend
plt.show()  # Show the plot